##### Copyright 2019 The TensorFlow Authors.

In [ ]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# TensorFlow 2 quickstart for beginners

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://www.tensorflow.org/tutorials/quickstart/beginner"><img src="https://www.tensorflow.org/images/tf_logo_32px.png" />View on TensorFlow.org</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/docs/site/en/tutorials/quickstart/beginner.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
</table>

This short introduction uses [Keras](https://www.tensorflow.org/guide/keras/overview) to:

1. Build a neural network that classifies images.
2. Train this neural network.
3. And, finally, evaluate the accuracy of the model.

This is a [Google Colaboratory](https://colab.research.google.com/notebooks/welcome.ipynb) notebook file. Python programs are run directly in the browser—a great way to learn and use TensorFlow. To follow this tutorial, run the notebook in Google Colab by clicking the button at the top of this page.

1. In Colab, connect to a Python runtime: At the top-right of the menu bar, select *CONNECT*.
2. Run all the notebook code cells: Select *Runtime* > *Run all*.

Download and install TensorFlow 2. Import TensorFlow into your program:

Note: Upgrade `pip` to install the TensorFlow 2 package. See the [install guide](https://www.tensorflow.org/install) for details.

In [1]:
import tensorflow as tf

Load and prepare the [MNIST dataset](http://yann.lecun.com/exdb/mnist/). Convert the samples from integers to floating-point numbers:

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11501568/11490434 [==============================] - 0s 0us/step


Build the `tf.keras.Sequential` model by stacking layers. Choose an optimizer and loss function for training:

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),# turn it into 1 d string
  tf.keras.layers.Dense(128, activation='relu'),# build a dense layer, create connection between our model
  tf.keras.layers.Dropout(0.2), # kill some connection if kill some connection help the overheat,
  tf.keras.layers.Dense(10) # have another dense layer
])

# didnt take anytime, just telling them what our model look like(assign variable), not actully doing things 

For each example the model returns a vector of "[logits](https://developers.google.com/machine-learning/glossary#logits)" or "[log-odds](https://developers.google.com/machine-learning/glossary#log-odds)" scores, one for each class.

In [4]:
predictions = model(x_train[:1]).numpy()
predictions


array([[-0.2367146 , -0.6336462 , -0.45959234,  0.5337885 , -0.12846488,
         0.0626158 , -0.45281073, -0.22853585, -0.10969369, -0.17852984]],
      dtype=float32)

The `tf.nn.softmax` function converts these logits to "probabilities" for each class: 

In [5]:
tf.nn.softmax(predictions).numpy()# turn them into probability, allow math to work here

array([[0.09004183, 0.06054233, 0.07205261, 0.19456717, 0.10033596,
        0.1214624 , 0.07254291, 0.09078129, 0.10223716, 0.0954363 ]],
      dtype=float32)

Note: It is possible to bake this `tf.nn.softmax` in as the activation function for the last layer of the network. While this can make the model output more directly interpretable, this approach is discouraged as it's impossible to
provide an exact and numerically stable loss calculation for all models when using a softmax output. 

The `losses.SparseCategoricalCrossentropy` loss takes a vector of logits and a `True` index and returns a scalar loss for each example.

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


# what are the weight of these connection, how to get to the weight effiectively 
# when start off the model, random number will be picked
# process of fit that gets from that number to that number
# different metod , is this the best number, no one knows - trying to get the better fit
# math is trying to figure out how to start and get the number

This loss is equal to the negative log probability of the true class:
It is zero if the model is sure of the correct class.

This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to `-tf.math.log(1/10) ~= 2.3`.

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

In [7]:
model.compile(optimizer='adam', 
              

#Image result for optimizer='adam'
#Adam is a replacement optimization algorithm for stochastic gradient descent 
#for training deep learning models. 
#Adam combines the best properties of the AdaGrad 
#and RMSProp algorithms to provide an optimization algorithm that can handle 
#sparse gradients on noisy problems.



              loss=loss_fn,
              metrics=['accuracy'])

The `Model.fit` method adjusts the model parameters to minimize the loss: 

In [8]:
model.fit(x_train, y_train, epochs=5)# this is to figure out how well is our model doing

#start with big change and gets to smaller change 
# diminishing return, there is a limit in terms of when you call it quit
# google might have run it longer becuase they always want to improve stuff
# the quality of data isn't good enough for .001
# judgemental call in terms of where you want to stop
# supervised method we have labeled training data, any classifer will be consider supervised method



Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2924 - accuracy: 0.9159
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1400 - accuracy: 0.9588
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1056 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0862 - accuracy: 0.9736
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0747 - accuracy: 0.9762


The `Model.evaluate` method checks the models performance, usually on a "[Validation-set](https://developers.google.com/machine-learning/glossary#validation-set)" or "[Test-set](https://developers.google.com/machine-learning/glossary#test-set)".

In [9]:
model.evaluate(x_test,  y_test, verbose=2). 

# evaluate our model if we rerun this, we will get differret accuracy number 
# becuase the fist number is picked at random

313/313 - 0s - loss: 0.0754 - accuracy: 0.9765


[0.07539926469326019, 0.9764999747276306]

The image classifier is now trained to ~98% accuracy on this dataset. To learn more, read the [TensorFlow tutorials](https://www.tensorflow.org/tutorials/).

If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:

In [10]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [11]:
probability_model(x_test[:5])


# array, prediction model, are these. how likely this one image to be a zero, is what this probability output are
# give your inital set of weight interms of how this things should be connected
# tensorflow - raster, giving you a set of weight for looking at raster data thats gonna be comming in
# turn into a numpy arrary, get a tensor (same things)
# 4 by 4 go to 2 by 2 - pooling(reduce the pixel size)



# a dense layer with dropout


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.30594410e-09, 4.90888941e-10, 8.78771516e-06, 1.62404285e-05,
        2.13650417e-10, 1.24009631e-07, 9.27399000e-13, 9.99973059e-01,
        1.15146679e-06, 5.86144665e-07],
       [2.46386776e-06, 3.95937714e-05, 9.99928594e-01, 2.57147440e-05,
        8.60885324e-15, 6.87522629e-07, 5.78612060e-07, 2.61528863e-13,
        2.32354455e-06, 8.24312081e-13],
       [9.37306311e-07, 9.96609747e-01, 2.28929319e-04, 2.69667635e-05,
        1.72832937e-04, 1.00903217e-05, 7.63544303e-05, 2.56518321e-03,
        3.06239061e-04, 2.66468078e-06],
       [9.99733508e-01, 1.65078817e-09, 1.87079801e-04, 6.75430059e-08,
        2.34850205e-07, 1.31240768e-06, 6.61623999e-05, 5.22748905e-06,
        1.17479191e-08, 6.43758449e-06],
       [1.27721728e-06, 5.05561426e-11, 1.47761455e-06, 6.45273630e-08,
        9.99197900e-01, 1.09196534e-07, 5.56090129e-07, 6.10926727e-05,
        9.80607183e-07, 7.36624177e-04]], dtype=float32)>